apiVersion: v1
kind: Service
metadata:
  name: numbering-parts-service
spec:
  selector:
    app: numbering-parts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 19090
  type: LoadBalancer